#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMovie.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Movie")]
	public partial class MovieDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCOMMENT(COMMENT instance);
    partial void UpdateCOMMENT(COMMENT instance);
    partial void DeleteCOMMENT(COMMENT instance);
    partial void InsertCHITIETDONHANG(CHITIETDONHANG instance);
    partial void UpdateCHITIETDONHANG(CHITIETDONHANG instance);
    partial void DeleteCHITIETDONHANG(CHITIETDONHANG instance);
    partial void InsertDONHANG(DONHANG instance);
    partial void UpdateDONHANG(DONHANG instance);
    partial void DeleteDONHANG(DONHANG instance);
    partial void InsertKHACHHANG(KHACHHANG instance);
    partial void UpdateKHACHHANG(KHACHHANG instance);
    partial void DeleteKHACHHANG(KHACHHANG instance);
    partial void InsertLICHSU(LICHSU instance);
    partial void UpdateLICHSU(LICHSU instance);
    partial void DeleteLICHSU(LICHSU instance);
    partial void InsertNAMPHATHANH(NAMPHATHANH instance);
    partial void UpdateNAMPHATHANH(NAMPHATHANH instance);
    partial void DeleteNAMPHATHANH(NAMPHATHANH instance);
    partial void InsertQUOCGIA(QUOCGIA instance);
    partial void UpdateQUOCGIA(QUOCGIA instance);
    partial void DeleteQUOCGIA(QUOCGIA instance);
    partial void InsertPHIM(PHIM instance);
    partial void UpdatePHIM(PHIM instance);
    partial void DeletePHIM(PHIM instance);
    partial void InsertQUYEN(QUYEN instance);
    partial void UpdateQUYEN(QUYEN instance);
    partial void DeleteQUYEN(QUYEN instance);
    partial void InsertTHE(THE instance);
    partial void UpdateTHE(THE instance);
    partial void DeleteTHE(THE instance);
    partial void InsertTHELOAI(THELOAI instance);
    partial void UpdateTHELOAI(THELOAI instance);
    partial void DeleteTHELOAI(THELOAI instance);
    #endregion
		
		public MovieDataDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["MovieConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MovieDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MovieDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MovieDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MovieDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<COMMENT> COMMENTs
		{
			get
			{
				return this.GetTable<COMMENT>();
			}
		}
		
		public System.Data.Linq.Table<CHITIETDONHANG> CHITIETDONHANGs
		{
			get
			{
				return this.GetTable<CHITIETDONHANG>();
			}
		}
		
		public System.Data.Linq.Table<DONHANG> DONHANGs
		{
			get
			{
				return this.GetTable<DONHANG>();
			}
		}
		
		public System.Data.Linq.Table<KHACHHANG> KHACHHANGs
		{
			get
			{
				return this.GetTable<KHACHHANG>();
			}
		}
		
		public System.Data.Linq.Table<LICHSU> LICHSUs
		{
			get
			{
				return this.GetTable<LICHSU>();
			}
		}
		
		public System.Data.Linq.Table<NAMPHATHANH> NAMPHATHANHs
		{
			get
			{
				return this.GetTable<NAMPHATHANH>();
			}
		}
		
		public System.Data.Linq.Table<QUOCGIA> QUOCGIAs
		{
			get
			{
				return this.GetTable<QUOCGIA>();
			}
		}
		
		public System.Data.Linq.Table<PHIM> PHIMs
		{
			get
			{
				return this.GetTable<PHIM>();
			}
		}
		
		public System.Data.Linq.Table<QUYEN> QUYENs
		{
			get
			{
				return this.GetTable<QUYEN>();
			}
		}
		
		public System.Data.Linq.Table<THE> THEs
		{
			get
			{
				return this.GetTable<THE>();
			}
		}
		
		public System.Data.Linq.Table<THELOAI> THELOAIs
		{
			get
			{
				return this.GetTable<THELOAI>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.COMMENTS")]
	public partial class COMMENT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaBL;
		
		private System.Nullable<int> _Makh;
		
		private System.Nullable<int> _Maphim;
		
		private string _Binhluan;
		
		private System.Nullable<System.DateTime> _thoigian;
		
		private System.Nullable<int> _Macha;
		
		private System.Nullable<int> _Danhgia;
		
		private EntitySet<COMMENT> _COMMENTs;
		
		private EntityRef<COMMENT> _COMMENT1;
		
		private EntityRef<KHACHHANG> _KHACHHANG;
		
		private EntityRef<PHIM> _PHIM;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaBLChanging(int value);
    partial void OnMaBLChanged();
    partial void OnMakhChanging(System.Nullable<int> value);
    partial void OnMakhChanged();
    partial void OnMaphimChanging(System.Nullable<int> value);
    partial void OnMaphimChanged();
    partial void OnBinhluanChanging(string value);
    partial void OnBinhluanChanged();
    partial void OnthoigianChanging(System.Nullable<System.DateTime> value);
    partial void OnthoigianChanged();
    partial void OnMachaChanging(System.Nullable<int> value);
    partial void OnMachaChanged();
    partial void OnDanhgiaChanging(System.Nullable<int> value);
    partial void OnDanhgiaChanged();
    #endregion
		
		public COMMENT()
		{
			this._COMMENTs = new EntitySet<COMMENT>(new Action<COMMENT>(this.attach_COMMENTs), new Action<COMMENT>(this.detach_COMMENTs));
			this._COMMENT1 = default(EntityRef<COMMENT>);
			this._KHACHHANG = default(EntityRef<KHACHHANG>);
			this._PHIM = default(EntityRef<PHIM>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBL", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaBL
		{
			get
			{
				return this._MaBL;
			}
			set
			{
				if ((this._MaBL != value))
				{
					this.OnMaBLChanging(value);
					this.SendPropertyChanging();
					this._MaBL = value;
					this.SendPropertyChanged("MaBL");
					this.OnMaBLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Makh", DbType="Int")]
		public System.Nullable<int> Makh
		{
			get
			{
				return this._Makh;
			}
			set
			{
				if ((this._Makh != value))
				{
					if (this._KHACHHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMakhChanging(value);
					this.SendPropertyChanging();
					this._Makh = value;
					this.SendPropertyChanged("Makh");
					this.OnMakhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Maphim", DbType="Int")]
		public System.Nullable<int> Maphim
		{
			get
			{
				return this._Maphim;
			}
			set
			{
				if ((this._Maphim != value))
				{
					if (this._PHIM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaphimChanging(value);
					this.SendPropertyChanging();
					this._Maphim = value;
					this.SendPropertyChanged("Maphim");
					this.OnMaphimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Binhluan", DbType="NVarChar(300)")]
		public string Binhluan
		{
			get
			{
				return this._Binhluan;
			}
			set
			{
				if ((this._Binhluan != value))
				{
					this.OnBinhluanChanging(value);
					this.SendPropertyChanging();
					this._Binhluan = value;
					this.SendPropertyChanged("Binhluan");
					this.OnBinhluanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thoigian", DbType="DateTime")]
		public System.Nullable<System.DateTime> thoigian
		{
			get
			{
				return this._thoigian;
			}
			set
			{
				if ((this._thoigian != value))
				{
					this.OnthoigianChanging(value);
					this.SendPropertyChanging();
					this._thoigian = value;
					this.SendPropertyChanged("thoigian");
					this.OnthoigianChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Macha", DbType="Int")]
		public System.Nullable<int> Macha
		{
			get
			{
				return this._Macha;
			}
			set
			{
				if ((this._Macha != value))
				{
					if (this._COMMENT1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMachaChanging(value);
					this.SendPropertyChanging();
					this._Macha = value;
					this.SendPropertyChanged("Macha");
					this.OnMachaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Danhgia", DbType="Int")]
		public System.Nullable<int> Danhgia
		{
			get
			{
				return this._Danhgia;
			}
			set
			{
				if ((this._Danhgia != value))
				{
					this.OnDanhgiaChanging(value);
					this.SendPropertyChanging();
					this._Danhgia = value;
					this.SendPropertyChanged("Danhgia");
					this.OnDanhgiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="COMMENT_COMMENT", Storage="_COMMENTs", ThisKey="MaBL", OtherKey="Macha")]
		public EntitySet<COMMENT> COMMENTs
		{
			get
			{
				return this._COMMENTs;
			}
			set
			{
				this._COMMENTs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="COMMENT_COMMENT", Storage="_COMMENT1", ThisKey="Macha", OtherKey="MaBL", IsForeignKey=true)]
		public COMMENT COMMENT1
		{
			get
			{
				return this._COMMENT1.Entity;
			}
			set
			{
				COMMENT previousValue = this._COMMENT1.Entity;
				if (((previousValue != value) 
							|| (this._COMMENT1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._COMMENT1.Entity = null;
						previousValue.COMMENTs.Remove(this);
					}
					this._COMMENT1.Entity = value;
					if ((value != null))
					{
						value.COMMENTs.Add(this);
						this._Macha = value.MaBL;
					}
					else
					{
						this._Macha = default(Nullable<int>);
					}
					this.SendPropertyChanged("COMMENT1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_COMMENT", Storage="_KHACHHANG", ThisKey="Makh", OtherKey="MaKh", IsForeignKey=true, DeleteRule="CASCADE")]
		public KHACHHANG KHACHHANG
		{
			get
			{
				return this._KHACHHANG.Entity;
			}
			set
			{
				KHACHHANG previousValue = this._KHACHHANG.Entity;
				if (((previousValue != value) 
							|| (this._KHACHHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHACHHANG.Entity = null;
						previousValue.COMMENTs.Remove(this);
					}
					this._KHACHHANG.Entity = value;
					if ((value != null))
					{
						value.COMMENTs.Add(this);
						this._Makh = value.MaKh;
					}
					else
					{
						this._Makh = default(Nullable<int>);
					}
					this.SendPropertyChanged("KHACHHANG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHIM_COMMENT", Storage="_PHIM", ThisKey="Maphim", OtherKey="Maphim", IsForeignKey=true, DeleteRule="CASCADE")]
		public PHIM PHIM
		{
			get
			{
				return this._PHIM.Entity;
			}
			set
			{
				PHIM previousValue = this._PHIM.Entity;
				if (((previousValue != value) 
							|| (this._PHIM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHIM.Entity = null;
						previousValue.COMMENTs.Remove(this);
					}
					this._PHIM.Entity = value;
					if ((value != null))
					{
						value.COMMENTs.Add(this);
						this._Maphim = value.Maphim;
					}
					else
					{
						this._Maphim = default(Nullable<int>);
					}
					this.SendPropertyChanged("PHIM");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_COMMENTs(COMMENT entity)
		{
			this.SendPropertyChanging();
			entity.COMMENT1 = this;
		}
		
		private void detach_COMMENTs(COMMENT entity)
		{
			this.SendPropertyChanging();
			entity.COMMENT1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHITIETDONHANG")]
	public partial class CHITIETDONHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaDH;
		
		private System.Nullable<int> _Soluong;
		
		private System.Nullable<decimal> _Dongia;
		
		private int _Mathe;
		
		private EntityRef<DONHANG> _DONHANG;
		
		private EntityRef<THE> _THE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDHChanging(int value);
    partial void OnMaDHChanged();
    partial void OnSoluongChanging(System.Nullable<int> value);
    partial void OnSoluongChanged();
    partial void OnDongiaChanging(System.Nullable<decimal> value);
    partial void OnDongiaChanged();
    partial void OnMatheChanging(int value);
    partial void OnMatheChanged();
    #endregion
		
		public CHITIETDONHANG()
		{
			this._DONHANG = default(EntityRef<DONHANG>);
			this._THE = default(EntityRef<THE>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDH", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaDH
		{
			get
			{
				return this._MaDH;
			}
			set
			{
				if ((this._MaDH != value))
				{
					if (this._DONHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDHChanging(value);
					this.SendPropertyChanging();
					this._MaDH = value;
					this.SendPropertyChanged("MaDH");
					this.OnMaDHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soluong", DbType="Int")]
		public System.Nullable<int> Soluong
		{
			get
			{
				return this._Soluong;
			}
			set
			{
				if ((this._Soluong != value))
				{
					this.OnSoluongChanging(value);
					this.SendPropertyChanging();
					this._Soluong = value;
					this.SendPropertyChanged("Soluong");
					this.OnSoluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dongia", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Dongia
		{
			get
			{
				return this._Dongia;
			}
			set
			{
				if ((this._Dongia != value))
				{
					this.OnDongiaChanging(value);
					this.SendPropertyChanging();
					this._Dongia = value;
					this.SendPropertyChanged("Dongia");
					this.OnDongiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mathe", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Mathe
		{
			get
			{
				return this._Mathe;
			}
			set
			{
				if ((this._Mathe != value))
				{
					if (this._THE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMatheChanging(value);
					this.SendPropertyChanging();
					this._Mathe = value;
					this.SendPropertyChanged("Mathe");
					this.OnMatheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DONHANG_CHITIETDONHANG", Storage="_DONHANG", ThisKey="MaDH", OtherKey="MaDH", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public DONHANG DONHANG
		{
			get
			{
				return this._DONHANG.Entity;
			}
			set
			{
				DONHANG previousValue = this._DONHANG.Entity;
				if (((previousValue != value) 
							|| (this._DONHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DONHANG.Entity = null;
						previousValue.CHITIETDONHANGs.Remove(this);
					}
					this._DONHANG.Entity = value;
					if ((value != null))
					{
						value.CHITIETDONHANGs.Add(this);
						this._MaDH = value.MaDH;
					}
					else
					{
						this._MaDH = default(int);
					}
					this.SendPropertyChanged("DONHANG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THE_CHITIETDONHANG", Storage="_THE", ThisKey="Mathe", OtherKey="Mathe", IsForeignKey=true)]
		public THE THE
		{
			get
			{
				return this._THE.Entity;
			}
			set
			{
				THE previousValue = this._THE.Entity;
				if (((previousValue != value) 
							|| (this._THE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._THE.Entity = null;
						previousValue.CHITIETDONHANGs.Remove(this);
					}
					this._THE.Entity = value;
					if ((value != null))
					{
						value.CHITIETDONHANGs.Add(this);
						this._Mathe = value.Mathe;
					}
					else
					{
						this._Mathe = default(int);
					}
					this.SendPropertyChanged("THE");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DONHANG")]
	public partial class DONHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaDH;
		
		private System.Nullable<System.DateTime> _NgayDH;
		
		private System.Nullable<bool> _Trangthai;
		
		private int _Makh;
		
		private EntitySet<CHITIETDONHANG> _CHITIETDONHANGs;
		
		private EntityRef<KHACHHANG> _KHACHHANG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDHChanging(int value);
    partial void OnMaDHChanged();
    partial void OnNgayDHChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayDHChanged();
    partial void OnTrangthaiChanging(System.Nullable<bool> value);
    partial void OnTrangthaiChanged();
    partial void OnMakhChanging(int value);
    partial void OnMakhChanged();
    #endregion
		
		public DONHANG()
		{
			this._CHITIETDONHANGs = new EntitySet<CHITIETDONHANG>(new Action<CHITIETDONHANG>(this.attach_CHITIETDONHANGs), new Action<CHITIETDONHANG>(this.detach_CHITIETDONHANGs));
			this._KHACHHANG = default(EntityRef<KHACHHANG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDH", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaDH
		{
			get
			{
				return this._MaDH;
			}
			set
			{
				if ((this._MaDH != value))
				{
					this.OnMaDHChanging(value);
					this.SendPropertyChanging();
					this._MaDH = value;
					this.SendPropertyChanged("MaDH");
					this.OnMaDHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDH", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayDH
		{
			get
			{
				return this._NgayDH;
			}
			set
			{
				if ((this._NgayDH != value))
				{
					this.OnNgayDHChanging(value);
					this.SendPropertyChanging();
					this._NgayDH = value;
					this.SendPropertyChanged("NgayDH");
					this.OnNgayDHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trangthai", DbType="Bit")]
		public System.Nullable<bool> Trangthai
		{
			get
			{
				return this._Trangthai;
			}
			set
			{
				if ((this._Trangthai != value))
				{
					this.OnTrangthaiChanging(value);
					this.SendPropertyChanging();
					this._Trangthai = value;
					this.SendPropertyChanged("Trangthai");
					this.OnTrangthaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Makh", DbType="Int NOT NULL")]
		public int Makh
		{
			get
			{
				return this._Makh;
			}
			set
			{
				if ((this._Makh != value))
				{
					if (this._KHACHHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMakhChanging(value);
					this.SendPropertyChanging();
					this._Makh = value;
					this.SendPropertyChanged("Makh");
					this.OnMakhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DONHANG_CHITIETDONHANG", Storage="_CHITIETDONHANGs", ThisKey="MaDH", OtherKey="MaDH")]
		public EntitySet<CHITIETDONHANG> CHITIETDONHANGs
		{
			get
			{
				return this._CHITIETDONHANGs;
			}
			set
			{
				this._CHITIETDONHANGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_DONHANG", Storage="_KHACHHANG", ThisKey="Makh", OtherKey="MaKh", IsForeignKey=true)]
		public KHACHHANG KHACHHANG
		{
			get
			{
				return this._KHACHHANG.Entity;
			}
			set
			{
				KHACHHANG previousValue = this._KHACHHANG.Entity;
				if (((previousValue != value) 
							|| (this._KHACHHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHACHHANG.Entity = null;
						previousValue.DONHANGs.Remove(this);
					}
					this._KHACHHANG.Entity = value;
					if ((value != null))
					{
						value.DONHANGs.Add(this);
						this._Makh = value.MaKh;
					}
					else
					{
						this._Makh = default(int);
					}
					this.SendPropertyChanged("KHACHHANG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHITIETDONHANGs(CHITIETDONHANG entity)
		{
			this.SendPropertyChanging();
			entity.DONHANG = this;
		}
		
		private void detach_CHITIETDONHANGs(CHITIETDONHANG entity)
		{
			this.SendPropertyChanging();
			entity.DONHANG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KHACHHANG")]
	public partial class KHACHHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaKh;
		
		private string _Taikhoan;
		
		private string _Matkhau;
		
		private string _Email;
		
		private string _DienthoaiKh;
		
		private System.Nullable<int> _MaQuyen;
		
		private string _Hoten;
		
		private EntitySet<COMMENT> _COMMENTs;
		
		private EntitySet<DONHANG> _DONHANGs;
		
		private EntitySet<LICHSU> _LICHSUs;
		
		private EntityRef<QUYEN> _QUYEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKhChanging(int value);
    partial void OnMaKhChanged();
    partial void OnTaikhoanChanging(string value);
    partial void OnTaikhoanChanged();
    partial void OnMatkhauChanging(string value);
    partial void OnMatkhauChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnDienthoaiKhChanging(string value);
    partial void OnDienthoaiKhChanged();
    partial void OnMaQuyenChanging(System.Nullable<int> value);
    partial void OnMaQuyenChanged();
    partial void OnHotenChanging(string value);
    partial void OnHotenChanged();
    #endregion
		
		public KHACHHANG()
		{
			this._COMMENTs = new EntitySet<COMMENT>(new Action<COMMENT>(this.attach_COMMENTs), new Action<COMMENT>(this.detach_COMMENTs));
			this._DONHANGs = new EntitySet<DONHANG>(new Action<DONHANG>(this.attach_DONHANGs), new Action<DONHANG>(this.detach_DONHANGs));
			this._LICHSUs = new EntitySet<LICHSU>(new Action<LICHSU>(this.attach_LICHSUs), new Action<LICHSU>(this.detach_LICHSUs));
			this._QUYEN = default(EntityRef<QUYEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKh", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaKh
		{
			get
			{
				return this._MaKh;
			}
			set
			{
				if ((this._MaKh != value))
				{
					this.OnMaKhChanging(value);
					this.SendPropertyChanging();
					this._MaKh = value;
					this.SendPropertyChanged("MaKh");
					this.OnMaKhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Taikhoan", DbType="VarChar(50)")]
		public string Taikhoan
		{
			get
			{
				return this._Taikhoan;
			}
			set
			{
				if ((this._Taikhoan != value))
				{
					this.OnTaikhoanChanging(value);
					this.SendPropertyChanging();
					this._Taikhoan = value;
					this.SendPropertyChanged("Taikhoan");
					this.OnTaikhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matkhau", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Matkhau
		{
			get
			{
				return this._Matkhau;
			}
			set
			{
				if ((this._Matkhau != value))
				{
					this.OnMatkhauChanging(value);
					this.SendPropertyChanging();
					this._Matkhau = value;
					this.SendPropertyChanged("Matkhau");
					this.OnMatkhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienthoaiKh", DbType="VarChar(50)")]
		public string DienthoaiKh
		{
			get
			{
				return this._DienthoaiKh;
			}
			set
			{
				if ((this._DienthoaiKh != value))
				{
					this.OnDienthoaiKhChanging(value);
					this.SendPropertyChanging();
					this._DienthoaiKh = value;
					this.SendPropertyChanged("DienthoaiKh");
					this.OnDienthoaiKhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaQuyen", DbType="Int")]
		public System.Nullable<int> MaQuyen
		{
			get
			{
				return this._MaQuyen;
			}
			set
			{
				if ((this._MaQuyen != value))
				{
					if (this._QUYEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaQuyenChanging(value);
					this.SendPropertyChanging();
					this._MaQuyen = value;
					this.SendPropertyChanged("MaQuyen");
					this.OnMaQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hoten", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Hoten
		{
			get
			{
				return this._Hoten;
			}
			set
			{
				if ((this._Hoten != value))
				{
					this.OnHotenChanging(value);
					this.SendPropertyChanging();
					this._Hoten = value;
					this.SendPropertyChanged("Hoten");
					this.OnHotenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_COMMENT", Storage="_COMMENTs", ThisKey="MaKh", OtherKey="Makh")]
		public EntitySet<COMMENT> COMMENTs
		{
			get
			{
				return this._COMMENTs;
			}
			set
			{
				this._COMMENTs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_DONHANG", Storage="_DONHANGs", ThisKey="MaKh", OtherKey="Makh")]
		public EntitySet<DONHANG> DONHANGs
		{
			get
			{
				return this._DONHANGs;
			}
			set
			{
				this._DONHANGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_LICHSU", Storage="_LICHSUs", ThisKey="MaKh", OtherKey="Makh")]
		public EntitySet<LICHSU> LICHSUs
		{
			get
			{
				return this._LICHSUs;
			}
			set
			{
				this._LICHSUs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QUYEN_KHACHHANG", Storage="_QUYEN", ThisKey="MaQuyen", OtherKey="MaQuyen", IsForeignKey=true)]
		public QUYEN QUYEN
		{
			get
			{
				return this._QUYEN.Entity;
			}
			set
			{
				QUYEN previousValue = this._QUYEN.Entity;
				if (((previousValue != value) 
							|| (this._QUYEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._QUYEN.Entity = null;
						previousValue.KHACHHANGs.Remove(this);
					}
					this._QUYEN.Entity = value;
					if ((value != null))
					{
						value.KHACHHANGs.Add(this);
						this._MaQuyen = value.MaQuyen;
					}
					else
					{
						this._MaQuyen = default(Nullable<int>);
					}
					this.SendPropertyChanged("QUYEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_COMMENTs(COMMENT entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = this;
		}
		
		private void detach_COMMENTs(COMMENT entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = null;
		}
		
		private void attach_DONHANGs(DONHANG entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = this;
		}
		
		private void detach_DONHANGs(DONHANG entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = null;
		}
		
		private void attach_LICHSUs(LICHSU entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = this;
		}
		
		private void detach_LICHSUs(LICHSU entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LICHSU")]
	public partial class LICHSU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Maphim;
		
		private int _Makh;
		
		private System.Nullable<System.DateTime> _Thoigian;
		
		private EntityRef<KHACHHANG> _KHACHHANG;
		
		private EntityRef<PHIM> _PHIM;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaphimChanging(int value);
    partial void OnMaphimChanged();
    partial void OnMakhChanging(int value);
    partial void OnMakhChanged();
    partial void OnThoigianChanging(System.Nullable<System.DateTime> value);
    partial void OnThoigianChanged();
    #endregion
		
		public LICHSU()
		{
			this._KHACHHANG = default(EntityRef<KHACHHANG>);
			this._PHIM = default(EntityRef<PHIM>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Maphim", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Maphim
		{
			get
			{
				return this._Maphim;
			}
			set
			{
				if ((this._Maphim != value))
				{
					if (this._PHIM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaphimChanging(value);
					this.SendPropertyChanging();
					this._Maphim = value;
					this.SendPropertyChanged("Maphim");
					this.OnMaphimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Makh", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Makh
		{
			get
			{
				return this._Makh;
			}
			set
			{
				if ((this._Makh != value))
				{
					if (this._KHACHHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMakhChanging(value);
					this.SendPropertyChanging();
					this._Makh = value;
					this.SendPropertyChanged("Makh");
					this.OnMakhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thoigian", DbType="DateTime")]
		public System.Nullable<System.DateTime> Thoigian
		{
			get
			{
				return this._Thoigian;
			}
			set
			{
				if ((this._Thoigian != value))
				{
					this.OnThoigianChanging(value);
					this.SendPropertyChanging();
					this._Thoigian = value;
					this.SendPropertyChanged("Thoigian");
					this.OnThoigianChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_LICHSU", Storage="_KHACHHANG", ThisKey="Makh", OtherKey="MaKh", IsForeignKey=true)]
		public KHACHHANG KHACHHANG
		{
			get
			{
				return this._KHACHHANG.Entity;
			}
			set
			{
				KHACHHANG previousValue = this._KHACHHANG.Entity;
				if (((previousValue != value) 
							|| (this._KHACHHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHACHHANG.Entity = null;
						previousValue.LICHSUs.Remove(this);
					}
					this._KHACHHANG.Entity = value;
					if ((value != null))
					{
						value.LICHSUs.Add(this);
						this._Makh = value.MaKh;
					}
					else
					{
						this._Makh = default(int);
					}
					this.SendPropertyChanged("KHACHHANG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHIM_LICHSU", Storage="_PHIM", ThisKey="Maphim", OtherKey="Maphim", IsForeignKey=true)]
		public PHIM PHIM
		{
			get
			{
				return this._PHIM.Entity;
			}
			set
			{
				PHIM previousValue = this._PHIM.Entity;
				if (((previousValue != value) 
							|| (this._PHIM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHIM.Entity = null;
						previousValue.LICHSUs.Remove(this);
					}
					this._PHIM.Entity = value;
					if ((value != null))
					{
						value.LICHSUs.Add(this);
						this._Maphim = value.Maphim;
					}
					else
					{
						this._Maphim = default(int);
					}
					this.SendPropertyChanged("PHIM");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NAMPHATHANH")]
	public partial class NAMPHATHANH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaNam;
		
		private string _Nam;
		
		private EntitySet<PHIM> _PHIMs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNamChanging(int value);
    partial void OnMaNamChanged();
    partial void OnNamChanging(string value);
    partial void OnNamChanged();
    #endregion
		
		public NAMPHATHANH()
		{
			this._PHIMs = new EntitySet<PHIM>(new Action<PHIM>(this.attach_PHIMs), new Action<PHIM>(this.detach_PHIMs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNam", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaNam
		{
			get
			{
				return this._MaNam;
			}
			set
			{
				if ((this._MaNam != value))
				{
					this.OnMaNamChanging(value);
					this.SendPropertyChanging();
					this._MaNam = value;
					this.SendPropertyChanged("MaNam");
					this.OnMaNamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nam", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string Nam
		{
			get
			{
				return this._Nam;
			}
			set
			{
				if ((this._Nam != value))
				{
					this.OnNamChanging(value);
					this.SendPropertyChanging();
					this._Nam = value;
					this.SendPropertyChanged("Nam");
					this.OnNamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NAMPHATHANH_PHIM", Storage="_PHIMs", ThisKey="MaNam", OtherKey="MaNam")]
		public EntitySet<PHIM> PHIMs
		{
			get
			{
				return this._PHIMs;
			}
			set
			{
				this._PHIMs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PHIMs(PHIM entity)
		{
			this.SendPropertyChanging();
			entity.NAMPHATHANH = this;
		}
		
		private void detach_PHIMs(PHIM entity)
		{
			this.SendPropertyChanging();
			entity.NAMPHATHANH = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QUOCGIA")]
	public partial class QUOCGIA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaQG;
		
		private string _TenQG;
		
		private EntitySet<PHIM> _PHIMs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaQGChanging(int value);
    partial void OnMaQGChanged();
    partial void OnTenQGChanging(string value);
    partial void OnTenQGChanged();
    #endregion
		
		public QUOCGIA()
		{
			this._PHIMs = new EntitySet<PHIM>(new Action<PHIM>(this.attach_PHIMs), new Action<PHIM>(this.detach_PHIMs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaQG", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaQG
		{
			get
			{
				return this._MaQG;
			}
			set
			{
				if ((this._MaQG != value))
				{
					this.OnMaQGChanging(value);
					this.SendPropertyChanging();
					this._MaQG = value;
					this.SendPropertyChanged("MaQG");
					this.OnMaQGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenQG", DbType="NVarChar(50)")]
		public string TenQG
		{
			get
			{
				return this._TenQG;
			}
			set
			{
				if ((this._TenQG != value))
				{
					this.OnTenQGChanging(value);
					this.SendPropertyChanging();
					this._TenQG = value;
					this.SendPropertyChanged("TenQG");
					this.OnTenQGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QUOCGIA_PHIM", Storage="_PHIMs", ThisKey="MaQG", OtherKey="MaQG")]
		public EntitySet<PHIM> PHIMs
		{
			get
			{
				return this._PHIMs;
			}
			set
			{
				this._PHIMs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PHIMs(PHIM entity)
		{
			this.SendPropertyChanging();
			entity.QUOCGIA = this;
		}
		
		private void detach_PHIMs(PHIM entity)
		{
			this.SendPropertyChanging();
			entity.QUOCGIA = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHIM")]
	public partial class PHIM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Maphim;
		
		private string _TenPhim;
		
		private string _Daodien;
		
		private string _Dienvien;
		
		private string _Noidung;
		
		private string _Dotuoi;
		
		private string _Thoiluong;
		
		private string _Ngonngu;
		
		private string _Linkphim;
		
		private string _Trailer;
		
		private System.Nullable<int> _MaNam;
		
		private System.Nullable<int> _MaQG;
		
		private string _Anhbia;
		
		private System.Nullable<bool> _Phimbo;
		
		private System.Nullable<int> _Phanphim;
		
		private System.Nullable<int> _Tapphim;
		
		private System.Nullable<int> _MaTL;
		
		private EntitySet<COMMENT> _COMMENTs;
		
		private EntitySet<LICHSU> _LICHSUs;
		
		private EntityRef<NAMPHATHANH> _NAMPHATHANH;
		
		private EntityRef<QUOCGIA> _QUOCGIA;
		
		private EntityRef<THELOAI> _THELOAI;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaphimChanging(int value);
    partial void OnMaphimChanged();
    partial void OnTenPhimChanging(string value);
    partial void OnTenPhimChanged();
    partial void OnDaodienChanging(string value);
    partial void OnDaodienChanged();
    partial void OnDienvienChanging(string value);
    partial void OnDienvienChanged();
    partial void OnNoidungChanging(string value);
    partial void OnNoidungChanged();
    partial void OnDotuoiChanging(string value);
    partial void OnDotuoiChanged();
    partial void OnThoiluongChanging(string value);
    partial void OnThoiluongChanged();
    partial void OnNgonnguChanging(string value);
    partial void OnNgonnguChanged();
    partial void OnLinkphimChanging(string value);
    partial void OnLinkphimChanged();
    partial void OnTrailerChanging(string value);
    partial void OnTrailerChanged();
    partial void OnMaNamChanging(System.Nullable<int> value);
    partial void OnMaNamChanged();
    partial void OnMaQGChanging(System.Nullable<int> value);
    partial void OnMaQGChanged();
    partial void OnAnhbiaChanging(string value);
    partial void OnAnhbiaChanged();
    partial void OnPhimboChanging(System.Nullable<bool> value);
    partial void OnPhimboChanged();
    partial void OnPhanphimChanging(System.Nullable<int> value);
    partial void OnPhanphimChanged();
    partial void OnTapphimChanging(System.Nullable<int> value);
    partial void OnTapphimChanged();
    partial void OnMaTLChanging(System.Nullable<int> value);
    partial void OnMaTLChanged();
    #endregion
		
		public PHIM()
		{
			this._COMMENTs = new EntitySet<COMMENT>(new Action<COMMENT>(this.attach_COMMENTs), new Action<COMMENT>(this.detach_COMMENTs));
			this._LICHSUs = new EntitySet<LICHSU>(new Action<LICHSU>(this.attach_LICHSUs), new Action<LICHSU>(this.detach_LICHSUs));
			this._NAMPHATHANH = default(EntityRef<NAMPHATHANH>);
			this._QUOCGIA = default(EntityRef<QUOCGIA>);
			this._THELOAI = default(EntityRef<THELOAI>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Maphim", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Maphim
		{
			get
			{
				return this._Maphim;
			}
			set
			{
				if ((this._Maphim != value))
				{
					this.OnMaphimChanging(value);
					this.SendPropertyChanging();
					this._Maphim = value;
					this.SendPropertyChanged("Maphim");
					this.OnMaphimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenPhim", DbType="NVarChar(100)")]
		public string TenPhim
		{
			get
			{
				return this._TenPhim;
			}
			set
			{
				if ((this._TenPhim != value))
				{
					this.OnTenPhimChanging(value);
					this.SendPropertyChanging();
					this._TenPhim = value;
					this.SendPropertyChanged("TenPhim");
					this.OnTenPhimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Daodien", DbType="NVarChar(50)")]
		public string Daodien
		{
			get
			{
				return this._Daodien;
			}
			set
			{
				if ((this._Daodien != value))
				{
					this.OnDaodienChanging(value);
					this.SendPropertyChanging();
					this._Daodien = value;
					this.SendPropertyChanged("Daodien");
					this.OnDaodienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dienvien", DbType="NVarChar(200)")]
		public string Dienvien
		{
			get
			{
				return this._Dienvien;
			}
			set
			{
				if ((this._Dienvien != value))
				{
					this.OnDienvienChanging(value);
					this.SendPropertyChanging();
					this._Dienvien = value;
					this.SendPropertyChanged("Dienvien");
					this.OnDienvienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Noidung", DbType="NVarChar(MAX)")]
		public string Noidung
		{
			get
			{
				return this._Noidung;
			}
			set
			{
				if ((this._Noidung != value))
				{
					this.OnNoidungChanging(value);
					this.SendPropertyChanging();
					this._Noidung = value;
					this.SendPropertyChanged("Noidung");
					this.OnNoidungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dotuoi", DbType="Char(10)")]
		public string Dotuoi
		{
			get
			{
				return this._Dotuoi;
			}
			set
			{
				if ((this._Dotuoi != value))
				{
					this.OnDotuoiChanging(value);
					this.SendPropertyChanging();
					this._Dotuoi = value;
					this.SendPropertyChanged("Dotuoi");
					this.OnDotuoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thoiluong", DbType="NVarChar(20)")]
		public string Thoiluong
		{
			get
			{
				return this._Thoiluong;
			}
			set
			{
				if ((this._Thoiluong != value))
				{
					this.OnThoiluongChanging(value);
					this.SendPropertyChanging();
					this._Thoiluong = value;
					this.SendPropertyChanged("Thoiluong");
					this.OnThoiluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngonngu", DbType="NVarChar(50)")]
		public string Ngonngu
		{
			get
			{
				return this._Ngonngu;
			}
			set
			{
				if ((this._Ngonngu != value))
				{
					this.OnNgonnguChanging(value);
					this.SendPropertyChanging();
					this._Ngonngu = value;
					this.SendPropertyChanged("Ngonngu");
					this.OnNgonnguChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Linkphim", DbType="NVarChar(200)")]
		public string Linkphim
		{
			get
			{
				return this._Linkphim;
			}
			set
			{
				if ((this._Linkphim != value))
				{
					this.OnLinkphimChanging(value);
					this.SendPropertyChanging();
					this._Linkphim = value;
					this.SendPropertyChanged("Linkphim");
					this.OnLinkphimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trailer", DbType="NVarChar(MAX)")]
		public string Trailer
		{
			get
			{
				return this._Trailer;
			}
			set
			{
				if ((this._Trailer != value))
				{
					this.OnTrailerChanging(value);
					this.SendPropertyChanging();
					this._Trailer = value;
					this.SendPropertyChanged("Trailer");
					this.OnTrailerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNam", DbType="Int")]
		public System.Nullable<int> MaNam
		{
			get
			{
				return this._MaNam;
			}
			set
			{
				if ((this._MaNam != value))
				{
					if (this._NAMPHATHANH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNamChanging(value);
					this.SendPropertyChanging();
					this._MaNam = value;
					this.SendPropertyChanged("MaNam");
					this.OnMaNamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaQG", DbType="Int")]
		public System.Nullable<int> MaQG
		{
			get
			{
				return this._MaQG;
			}
			set
			{
				if ((this._MaQG != value))
				{
					if (this._QUOCGIA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaQGChanging(value);
					this.SendPropertyChanging();
					this._MaQG = value;
					this.SendPropertyChanged("MaQG");
					this.OnMaQGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anhbia", DbType="VarChar(50)")]
		public string Anhbia
		{
			get
			{
				return this._Anhbia;
			}
			set
			{
				if ((this._Anhbia != value))
				{
					this.OnAnhbiaChanging(value);
					this.SendPropertyChanging();
					this._Anhbia = value;
					this.SendPropertyChanged("Anhbia");
					this.OnAnhbiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phimbo", DbType="Bit")]
		public System.Nullable<bool> Phimbo
		{
			get
			{
				return this._Phimbo;
			}
			set
			{
				if ((this._Phimbo != value))
				{
					this.OnPhimboChanging(value);
					this.SendPropertyChanging();
					this._Phimbo = value;
					this.SendPropertyChanged("Phimbo");
					this.OnPhimboChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phanphim", DbType="Int")]
		public System.Nullable<int> Phanphim
		{
			get
			{
				return this._Phanphim;
			}
			set
			{
				if ((this._Phanphim != value))
				{
					this.OnPhanphimChanging(value);
					this.SendPropertyChanging();
					this._Phanphim = value;
					this.SendPropertyChanged("Phanphim");
					this.OnPhanphimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tapphim", DbType="Int")]
		public System.Nullable<int> Tapphim
		{
			get
			{
				return this._Tapphim;
			}
			set
			{
				if ((this._Tapphim != value))
				{
					this.OnTapphimChanging(value);
					this.SendPropertyChanging();
					this._Tapphim = value;
					this.SendPropertyChanged("Tapphim");
					this.OnTapphimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTL", DbType="Int")]
		public System.Nullable<int> MaTL
		{
			get
			{
				return this._MaTL;
			}
			set
			{
				if ((this._MaTL != value))
				{
					if (this._THELOAI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTLChanging(value);
					this.SendPropertyChanging();
					this._MaTL = value;
					this.SendPropertyChanged("MaTL");
					this.OnMaTLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHIM_COMMENT", Storage="_COMMENTs", ThisKey="Maphim", OtherKey="Maphim")]
		public EntitySet<COMMENT> COMMENTs
		{
			get
			{
				return this._COMMENTs;
			}
			set
			{
				this._COMMENTs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHIM_LICHSU", Storage="_LICHSUs", ThisKey="Maphim", OtherKey="Maphim")]
		public EntitySet<LICHSU> LICHSUs
		{
			get
			{
				return this._LICHSUs;
			}
			set
			{
				this._LICHSUs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NAMPHATHANH_PHIM", Storage="_NAMPHATHANH", ThisKey="MaNam", OtherKey="MaNam", IsForeignKey=true)]
		public NAMPHATHANH NAMPHATHANH
		{
			get
			{
				return this._NAMPHATHANH.Entity;
			}
			set
			{
				NAMPHATHANH previousValue = this._NAMPHATHANH.Entity;
				if (((previousValue != value) 
							|| (this._NAMPHATHANH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NAMPHATHANH.Entity = null;
						previousValue.PHIMs.Remove(this);
					}
					this._NAMPHATHANH.Entity = value;
					if ((value != null))
					{
						value.PHIMs.Add(this);
						this._MaNam = value.MaNam;
					}
					else
					{
						this._MaNam = default(Nullable<int>);
					}
					this.SendPropertyChanged("NAMPHATHANH");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QUOCGIA_PHIM", Storage="_QUOCGIA", ThisKey="MaQG", OtherKey="MaQG", IsForeignKey=true)]
		public QUOCGIA QUOCGIA
		{
			get
			{
				return this._QUOCGIA.Entity;
			}
			set
			{
				QUOCGIA previousValue = this._QUOCGIA.Entity;
				if (((previousValue != value) 
							|| (this._QUOCGIA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._QUOCGIA.Entity = null;
						previousValue.PHIMs.Remove(this);
					}
					this._QUOCGIA.Entity = value;
					if ((value != null))
					{
						value.PHIMs.Add(this);
						this._MaQG = value.MaQG;
					}
					else
					{
						this._MaQG = default(Nullable<int>);
					}
					this.SendPropertyChanged("QUOCGIA");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THELOAI_PHIM", Storage="_THELOAI", ThisKey="MaTL", OtherKey="MaTL", IsForeignKey=true)]
		public THELOAI THELOAI
		{
			get
			{
				return this._THELOAI.Entity;
			}
			set
			{
				THELOAI previousValue = this._THELOAI.Entity;
				if (((previousValue != value) 
							|| (this._THELOAI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._THELOAI.Entity = null;
						previousValue.PHIMs.Remove(this);
					}
					this._THELOAI.Entity = value;
					if ((value != null))
					{
						value.PHIMs.Add(this);
						this._MaTL = value.MaTL;
					}
					else
					{
						this._MaTL = default(Nullable<int>);
					}
					this.SendPropertyChanged("THELOAI");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_COMMENTs(COMMENT entity)
		{
			this.SendPropertyChanging();
			entity.PHIM = this;
		}
		
		private void detach_COMMENTs(COMMENT entity)
		{
			this.SendPropertyChanging();
			entity.PHIM = null;
		}
		
		private void attach_LICHSUs(LICHSU entity)
		{
			this.SendPropertyChanging();
			entity.PHIM = this;
		}
		
		private void detach_LICHSUs(LICHSU entity)
		{
			this.SendPropertyChanging();
			entity.PHIM = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QUYEN")]
	public partial class QUYEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaQuyen;
		
		private string _TenQuyen;
		
		private EntitySet<KHACHHANG> _KHACHHANGs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaQuyenChanging(int value);
    partial void OnMaQuyenChanged();
    partial void OnTenQuyenChanging(string value);
    partial void OnTenQuyenChanged();
    #endregion
		
		public QUYEN()
		{
			this._KHACHHANGs = new EntitySet<KHACHHANG>(new Action<KHACHHANG>(this.attach_KHACHHANGs), new Action<KHACHHANG>(this.detach_KHACHHANGs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaQuyen", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaQuyen
		{
			get
			{
				return this._MaQuyen;
			}
			set
			{
				if ((this._MaQuyen != value))
				{
					this.OnMaQuyenChanging(value);
					this.SendPropertyChanging();
					this._MaQuyen = value;
					this.SendPropertyChanged("MaQuyen");
					this.OnMaQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenQuyen", DbType="Char(10)")]
		public string TenQuyen
		{
			get
			{
				return this._TenQuyen;
			}
			set
			{
				if ((this._TenQuyen != value))
				{
					this.OnTenQuyenChanging(value);
					this.SendPropertyChanging();
					this._TenQuyen = value;
					this.SendPropertyChanged("TenQuyen");
					this.OnTenQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QUYEN_KHACHHANG", Storage="_KHACHHANGs", ThisKey="MaQuyen", OtherKey="MaQuyen")]
		public EntitySet<KHACHHANG> KHACHHANGs
		{
			get
			{
				return this._KHACHHANGs;
			}
			set
			{
				this._KHACHHANGs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KHACHHANGs(KHACHHANG entity)
		{
			this.SendPropertyChanging();
			entity.QUYEN = this;
		}
		
		private void detach_KHACHHANGs(KHACHHANG entity)
		{
			this.SendPropertyChanging();
			entity.QUYEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THE")]
	public partial class THE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Mathe;
		
		private string _LoaiThe;
		
		private System.Nullable<decimal> _GiaTien;
		
		private string _ChatLuong;
		
		private string _PhanGiai;
		
		private EntitySet<CHITIETDONHANG> _CHITIETDONHANGs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMatheChanging(int value);
    partial void OnMatheChanged();
    partial void OnLoaiTheChanging(string value);
    partial void OnLoaiTheChanged();
    partial void OnGiaTienChanging(System.Nullable<decimal> value);
    partial void OnGiaTienChanged();
    partial void OnChatLuongChanging(string value);
    partial void OnChatLuongChanged();
    partial void OnPhanGiaiChanging(string value);
    partial void OnPhanGiaiChanged();
    #endregion
		
		public THE()
		{
			this._CHITIETDONHANGs = new EntitySet<CHITIETDONHANG>(new Action<CHITIETDONHANG>(this.attach_CHITIETDONHANGs), new Action<CHITIETDONHANG>(this.detach_CHITIETDONHANGs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mathe", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Mathe
		{
			get
			{
				return this._Mathe;
			}
			set
			{
				if ((this._Mathe != value))
				{
					this.OnMatheChanging(value);
					this.SendPropertyChanging();
					this._Mathe = value;
					this.SendPropertyChanged("Mathe");
					this.OnMatheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiThe", DbType="NVarChar(50)")]
		public string LoaiThe
		{
			get
			{
				return this._LoaiThe;
			}
			set
			{
				if ((this._LoaiThe != value))
				{
					this.OnLoaiTheChanging(value);
					this.SendPropertyChanging();
					this._LoaiThe = value;
					this.SendPropertyChanged("LoaiThe");
					this.OnLoaiTheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaTien", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> GiaTien
		{
			get
			{
				return this._GiaTien;
			}
			set
			{
				if ((this._GiaTien != value))
				{
					this.OnGiaTienChanging(value);
					this.SendPropertyChanging();
					this._GiaTien = value;
					this.SendPropertyChanged("GiaTien");
					this.OnGiaTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChatLuong", DbType="NVarChar(100)")]
		public string ChatLuong
		{
			get
			{
				return this._ChatLuong;
			}
			set
			{
				if ((this._ChatLuong != value))
				{
					this.OnChatLuongChanging(value);
					this.SendPropertyChanging();
					this._ChatLuong = value;
					this.SendPropertyChanged("ChatLuong");
					this.OnChatLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhanGiai", DbType="NChar(20)")]
		public string PhanGiai
		{
			get
			{
				return this._PhanGiai;
			}
			set
			{
				if ((this._PhanGiai != value))
				{
					this.OnPhanGiaiChanging(value);
					this.SendPropertyChanging();
					this._PhanGiai = value;
					this.SendPropertyChanged("PhanGiai");
					this.OnPhanGiaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THE_CHITIETDONHANG", Storage="_CHITIETDONHANGs", ThisKey="Mathe", OtherKey="Mathe")]
		public EntitySet<CHITIETDONHANG> CHITIETDONHANGs
		{
			get
			{
				return this._CHITIETDONHANGs;
			}
			set
			{
				this._CHITIETDONHANGs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHITIETDONHANGs(CHITIETDONHANG entity)
		{
			this.SendPropertyChanging();
			entity.THE = this;
		}
		
		private void detach_CHITIETDONHANGs(CHITIETDONHANG entity)
		{
			this.SendPropertyChanging();
			entity.THE = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THELOAI")]
	public partial class THELOAI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaTL;
		
		private string _TenTL;
		
		private EntitySet<PHIM> _PHIMs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTLChanging(int value);
    partial void OnMaTLChanged();
    partial void OnTenTLChanging(string value);
    partial void OnTenTLChanged();
    #endregion
		
		public THELOAI()
		{
			this._PHIMs = new EntitySet<PHIM>(new Action<PHIM>(this.attach_PHIMs), new Action<PHIM>(this.detach_PHIMs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTL", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaTL
		{
			get
			{
				return this._MaTL;
			}
			set
			{
				if ((this._MaTL != value))
				{
					this.OnMaTLChanging(value);
					this.SendPropertyChanging();
					this._MaTL = value;
					this.SendPropertyChanged("MaTL");
					this.OnMaTLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTL", DbType="NVarChar(50)")]
		public string TenTL
		{
			get
			{
				return this._TenTL;
			}
			set
			{
				if ((this._TenTL != value))
				{
					this.OnTenTLChanging(value);
					this.SendPropertyChanging();
					this._TenTL = value;
					this.SendPropertyChanged("TenTL");
					this.OnTenTLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THELOAI_PHIM", Storage="_PHIMs", ThisKey="MaTL", OtherKey="MaTL")]
		public EntitySet<PHIM> PHIMs
		{
			get
			{
				return this._PHIMs;
			}
			set
			{
				this._PHIMs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PHIMs(PHIM entity)
		{
			this.SendPropertyChanging();
			entity.THELOAI = this;
		}
		
		private void detach_PHIMs(PHIM entity)
		{
			this.SendPropertyChanging();
			entity.THELOAI = null;
		}
	}
}
#pragma warning restore 1591
